version: '3.6'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:3
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
    networks:
      - graylog
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    networks:
      - graylog
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:2.4.0-1
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://graylog.zitrolab.lan/api
    volumes:
      - /srv/docker/volumes/graylog:/usr/share/graylog/data/config
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9001:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
      - traefik
      - graylog
    deploy:
     labels:
        traefik.port: 9000
        traefik.docker.network: 'traefik'
        traefik.frontend.rule: 'Host:graylog.zitrolab.lan' 
  logspout:
    image: kpeiruza/logspout-multiline-gelf
    environment:
      ALLOW_TTY: 'true'
      MULTILINE_ENABLE_DEFAULT: 'true'
      MULTILINE_PATTERN: '^\d\d:\d\d:\d\d\.\d\d\d '
      MULTILINE_MATCH: 'first' #default nonfirst
      EXCLUDE_LABEL: 'logspout.exclude'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: multiline+gelf://graylog:12201
    networks:
      - graylog

networks:
  graylog:
  traefik:
    external: true
