version: '3.3'
  
services:
  php:
    depends_on:
      - redis
    image: asodrober/docker-php-redis-sessions:latest
    networks:
      - traefik
      - backend
    deploy:
      labels:
        traefik.port: 80
        traefik.docker.network: 'traefik'
        traefik.frontend.rule: 'Host:php-redis-sessions.zitrolab.lan'

  redis:
    image: redis:latest
    networks:
      - backend
networks:
  traefik:
    external: true
  backend:
